# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shf/OPRF-Garbled-Circuits/PQ-MPC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shf/OPRF-Garbled-Circuits/PQ-MPC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shf/OPRF-Garbled-Circuits/PQ-MPC/CMakeFiles /home/shf/OPRF-Garbled-Circuits/PQ-MPC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shf/OPRF-Garbled-Circuits/PQ-MPC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named emp-tool

# Build rule for target.
emp-tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 emp-tool
.PHONY : emp-tool

# fast build rule for target.
emp-tool/fast:
	$(MAKE) $(MAKESILENT) -f emp-tool/CMakeFiles/emp-tool.dir/build.make emp-tool/CMakeFiles/emp-tool.dir/build
.PHONY : emp-tool/fast

#=============================================================================
# Target rules for targets named pq-ot

# Build rule for target.
pq-ot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pq-ot
.PHONY : pq-ot

# fast build rule for target.
pq-ot/fast:
	$(MAKE) $(MAKESILENT) -f pq-ot/CMakeFiles/pq-ot.dir/build.make pq-ot/CMakeFiles/pq-ot.dir/build
.PHONY : pq-ot/fast

#=============================================================================
# Target rules for targets named pq-yao

# Build rule for target.
pq-yao: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pq-yao
.PHONY : pq-yao

# fast build rule for target.
pq-yao/fast:
	$(MAKE) $(MAKESILENT) -f pq-yao/CMakeFiles/pq-yao.dir/build.make pq-yao/CMakeFiles/pq-yao.dir/build
.PHONY : pq-yao/fast

#=============================================================================
# Target rules for targets named user_pq-oprf

# Build rule for target.
user_pq-oprf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 user_pq-oprf
.PHONY : user_pq-oprf

# fast build rule for target.
user_pq-oprf/fast:
	$(MAKE) $(MAKESILENT) -f pq-oprf/CMakeFiles/user_pq-oprf.dir/build.make pq-oprf/CMakeFiles/user_pq-oprf.dir/build
.PHONY : user_pq-oprf/fast

#=============================================================================
# Target rules for targets named server_pq-oprf

# Build rule for target.
server_pq-oprf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_pq-oprf
.PHONY : server_pq-oprf

# fast build rule for target.
server_pq-oprf/fast:
	$(MAKE) $(MAKESILENT) -f pq-oprf/CMakeFiles/server_pq-oprf.dir/build.make pq-oprf/CMakeFiles/server_pq-oprf.dir/build
.PHONY : server_pq-oprf/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... emp-tool"
	@echo "... pq-ot"
	@echo "... pq-yao"
	@echo "... server_pq-oprf"
	@echo "... user_pq-oprf"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

